name: Rust CI

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # 安装一个固定的 Rust 工具链版本，这让构建更稳定和可复现
    # 同时，显式安装 clippy 和 fmt 组件
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: 1.79.0 # 使用一个具体的稳定版本，例如 1.79.0
        components: clippy, fmt

    # 为 Cargo 设置缓存，极大提升后续运行速度
    - name: Cache Cargo dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    # 1. 检查代码格式
    - name: Check formatting
      run: cargo fmt --all -- --check

    # 2. 运行 Clippy 代码质量检查
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    # 3. 运行测试
    - name: Run tests
      run: cargo test --verbose --all-features

    # 4. 确保 Release 版本可以成功构建
    - name: Build release
      run: cargo build --release --all-features
    
    # 5. 检查是否可以打包（可选，但对库项目有益）
    - name: Check packaging
      run: cargo package --all-features

  # publish:
  #   name: Publish to Crates.io
  #   runs-on: ubuntu-latest
  #   needs: [check-and-test] # 依赖于上面的任务
  #   if: startsWith(github.ref, 'refs/tags/') # 只在创建 tag 时运行

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Install Rust toolchain
  #       uses: actions-rust-lang/setup-rust-toolchain@v1
  #       with:
  #         toolchain: 1.79.0 # 保持版本一致
  #     - name: Publish to Crates.io
  #       run: cargo publish
  #       env:
  #         CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}